//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_420_PopelyukEgorVal.DataBaseFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int ID_match { get; set; }
        public Nullable<int> ID_registr_one { get; set; }
        public Nullable<int> ID_registr_two { get; set; }
        public Nullable<int> Result { get; set; }
        public Nullable<int> CountDead { get; set; }
        public Nullable<System.TimeSpan> TimeGame { get; set; }
    
        public virtual Registration Registration { get; set; }
        public virtual Registration Registration1 { get; set; }
    }
}
